spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/narcissujsk/myspringcloudconfig
          search-paths: myconfigpath
          username: narcissujsk
          password: 385152jsk
      label: master
server:
  port: 4600


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true
