
eureka:
  server:
    enable-self-preservation: false
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    register-with-eureka: true
    fetchRegistry: false
server:
  port: 1111
