spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/narcissujsk/springboot/
          search-paths: config-repo
          username: narcissujsk
          password: 385152jsk
server:
  port: 7001


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true
